### ISSUE TITLE
Play_Store_Installer.sh Open G_APPS URL Change

### ISSUE THREAD

**Issue by angry-bender** [mkg20001/anbox-installer#1]
> OPENGAPPS_RELEASEDATE="$(curl -s https://api.github.com/repos/opengapps/x86_    64/releases/latest | head -n 10 | grep tag_name | grep -o "\"[0-9][0-9]*\""     | grep -o "[0-9]*")" # get latest releasedate based on tag_name for latest x    86_64 build

API Call fails 

  | "Not Found"
-- | --

`OPENGAPPS_FILE="open_gapps-x86_64-7.1-mini-$OPENGAPPS_RELEASEDATE.zip"
 32 
OPENGAPPS_URL="https://github.com/opengapps/x86_64/releases/download/$OPENGA    PPS_RELEASEDATE/$OPENGAPPS_FILE"
`
URL Has changed I.E https://excellmedia.dl.sourceforge.net/project/opengapps/x86_64/20190906/open_gapps-x86_64-7.1-stock-20190906.zip

**Comment by samfree91** [comment]
Updated Title

**Comment by mkg20001** [comment]
I have updated the external installer script

Update with `git pull --recurse-submodule`, close if it works.
